### ISSUE TITLE
one-liner-1.0 fails to build with GHC 9.0 and 9.2

### ISSUE THREAD

**Issue by sjakobi** [sjoerdvisscher/one-liner#19]
```
src/Generics/OneLiner/Internal.hs:72:12: error:
    • Could not deduce: p a b ~ (k p => p a b)
      from the context: Satisfies p (k : _ks)
        bound by the type signature for:
                   (|-) :: forall (p :: * -> * -> *)
                                  (proxy0 :: [(* -> * -> *) -> Constraint] -> *)
                                  (proxy1 :: ((* -> * -> *) -> Constraint) -> *) a b.
                           Satisfies p (k : _ks) =>
                           proxy0 (k : _ks) -> proxy1 k -> (k p => p a b) -> p a b
        at src/Generics/OneLiner/Internal.hs:72:5-6
      Expected: (k p => p a b) -> p a b
        Actual: p a b -> p a b
    • In the expression: id
      In an equation for ‘|-’: _ |- _ = id
      In the instance declaration for ‘(k : _ks) |- k’
    • Relevant bindings include
        (|-) :: proxy0 (k : _ks) -> proxy1 k -> (k p => p a b) -> p a b
          (bound at src/Generics/OneLiner/Internal.hs:72:5)
   |
72 |   _ |- _ = id
   |            ^^
cabal: Failed to build one-liner-1.0.
```

It would be good to revise this version in order to remove the invalid build plan. I'm don't quite understand the error though. If it's an incompatibility with GHC >= 9, how about adding a constraint `base < 4.15`?!

**Comment by sjoerdvisscher** [comment]
This is a simplified subsumption issue. Adding that constraint sounds like a good idea.

**Comment by sjoerdvisscher** [comment]
Fix with a new revision on Hackage.
